(()=>{'use strict';
const cfg=window.CLOUD_CONFIG||{},$=id=>document.getElementById(id),escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const endpoint=()=>`${String(cfg.supabaseUrl||'').replace(/\/$/,'')}/functions/v1/${cfg.functionName||'app-api'}`;
const configured=()=>/^https:\/\//.test(String(cfg.supabaseUrl||''))&&String(cfg.anonKey||'').length>20;
function secret(){return $('adminSecret').value.trim()}
function error(msg=''){ $('adminError').textContent=msg }
async function api(action,payload={}){if(!configured())throw new Error('cloud-config.js içindeki Supabase bilgileri eksik.');const r=await fetch(endpoint(),{method:'POST',headers:{'content-type':'application/json','apikey':cfg.anonKey},body:JSON.stringify({action,adminSecret:secret(),...payload})});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`Sunucu hatası (${r.status})`);return b}
function credentials(result,label='Yeni kullanıcı'){const box=$('adminCredentialResult');box.innerHTML=`<div class="admin-cred"><div><span>Kullanıcı adı</span><strong>${escapeHtml(result.username)}</strong></div><div><span>Sihirli kelime</span><strong>${escapeHtml(result.magicWord)}</strong></div><div><span>6 haneli kod</span><strong>${escapeHtml(result.accessCode)}</strong></div></div><div class="admin-warning">${escapeHtml(label)} bilgileri yalnızca şimdi açık metin gösterilir. Güvenli biçimde kullanıcıya ilet.</div>`}
async function load(){error();try{const r=await api('list-users');render(r.users||[])}catch(e){error(e.message)}}
function render(users){const box=$('adminUsers');if(!users.length){box.innerHTML='<div class="cloud-muted">Henüz kullanıcı yok.</div>';return}box.innerHTML=users.map(u=>`<div class="admin-user"><div><b>${escapeHtml(String(u.username).toUpperCase())}</b><div class="admin-meta">${u.disabled?'Devre dışı':'Aktif'} · ${Number(u.deviceCount)||0} cihaz · Son giriş: ${u.last_login_at?escapeHtml(new Date(u.last_login_at).toLocaleString('tr-TR')):'hiç'}</div></div><div class="admin-actions"><button class="modal-btn ghost" data-reset="${escapeHtml(u.username)}">Bilgileri Sıfırla</button><button class="modal-btn ghost" data-disable="${escapeHtml(u.username)}" data-value="${u.disabled?'0':'1'}">${u.disabled?'Etkinleştir':'Devre Dışı Bırak'}</button></div></div>`).join('');box.querySelectorAll('[data-reset]').forEach(btn=>btn.onclick=async()=>{if(!confirm(`${btn.dataset.reset} için yeni giriş bilgileri üretilecek ve tüm cihaz oturumları kapanacak. Devam?`))return;try{const r=await api('reset-user',{username:btn.dataset.reset});credentials(r,'Yenilenen giriş');await load()}catch(e){error(e.message)}});box.querySelectorAll('[data-disable]').forEach(btn=>btn.onclick=async()=>{try{await api('set-disabled',{username:btn.dataset.disable,disabled:btn.dataset.value==='1'});await load()}catch(e){error(e.message)}})}
$('adminLoad').onclick=load;$('adminRefresh').onclick=load;$('adminCreate').onclick=async()=>{error();if(!secret()){error('Önce yönetici anahtarını gir.');return}try{const r=await api('create-user');credentials(r);await load()}catch(e){error(e.message)}};
})();
